window:
  opacity: 0.75

font:
  # Point size
  #size: 16 # Work 4K Screen
  size: 10 # Home

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

schemes:
  alacritty_default: &alacritty_default
    # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'
      dim_foreground: '#828482'
      bright_foreground: '#eaeaea'

    # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc6666'
      green:   '#b5bd68'
      yellow:  '#f0c674'
      blue:    '#81a2be'
      magenta: '#b294bb'
      cyan:    '#8abeb7'
      white:   '#c5c8c6'

    # Bright colors
    bright:
      black:   '#666666'
      red:     '#d54e53'
      green:   '#b9ca4a'
      yellow:  '#e7c547'
      blue:    '#7aa6da'
      magenta: '#c397d8'
      cyan:    '#70c0b1'
      white:   '#eaeaea'

    # Dim colors
    dim:
      black:   '#131415'
      red:     '#864343'
      green:   '#777c44'
      yellow:  '#9e824c'
      blue:    '#556a7d'
      magenta: '#75617b'
      cyan:    '#5b7d78'
      white:   '#828482'

  basic_theme: &basic_theme
    # Default colors
    primary:
      background: '#000000'
      foreground: '#ffffff'
      dim_foreground: '#828482'
      bright_foreground: '#eaeaea'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#AA0000'
      green:   '#00AA00'
      yellow:  '#AA5500'
      blue:    '#0000AA'
      magenta: '#AA00AA'
      cyan:    '#00AAAA'
      white:   '#AAAAAA'

    # Bright colors
    bright:
      black:   '#555555'
      red:     '#FF5555'
      green:   '#55FF55'
      yellow:  '#FFFF55'
      blue:    '#5555FF'
      magenta: '#FF55FF'
      cyan:    '#55FFFF'
      white:   '#FFFFFF'

  tango_theme: &tango_theme
    # Default colors
    primary:
      background: '#000000'
      foreground: '#ffffff'
  
    # Normal colors
    normal:
      black:   '#2e3436'
      red:     '#cc0000'
      green:   '#73d216'
      yellow:  '#edd400'
      blue:    '#3465a4'
      magenta: '#75507b'
      cyan:    '#06989a'
      white:   '#d3d7cf'
  
    # Bright colors
    bright:
      black:   '#2e3436'
      red:     '#ef2929'
      green:   '#8ae234'
      yellow:  '#fce94f'
      blue:    '#729fcf'
      magenta: '#ad7fa8'
      cyan:    '#34e2e2'
      white:   '#eeeeec'

colors: *basic_theme

shell:
  program: /bin/bash
  args:
    - --login
    - -c
    - -i
    - tmux_connect

key_bindings:
  - { key: F11, command: { program: "wmctrl", args: ["-r", ":ACTIVE:", "-b", "toggle,fullscreen" ] } }
