# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# open (like on macos)
[ "$(uname)" == "Linux" ] && alias open='xdg-open'

# leet git man (useful when merging with 'gitls --unmerged')
function gitls () {
	if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
		git ls-files --help

	else
		echo $(git ls-files $@ | awk '{print $4}' | uniq);
	fi
}

# function to quickly connect to a tmux instance in ssh
function ssh_tmux() { ssh -t "$1" "tmux a || tmux"; }

# function to connect to detached tmux session or create a new one
function tmux_connect() {
	DETACHED_SESS=$(tmux list-session -F '#{session_name} #{?session_attached, attached, }' | grep -m 1 -v attached)

	if [ $DETACHED_SESS ]; then
			tmux attach-session -t $DETACHED_SESS
	else
			tmux
	fi
}

# makefile generator (42's C projects)
alias genmake="${HOME}/genmake/genmake"
